//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oceanic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Segment
    {
        public int Id { get; set; }
        public Nullable<decimal> Time { get; set; }
        public Nullable<int> StartLocationId { get; set; }
        public Nullable<int> EndLocationId { get; set; }
    
        public virtual Location EndLocation { get; set; }
        public virtual Location StartLocation { get; set; }
    }
}
